/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BbmsPack;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */
public class AdminEdit extends javax.swing.JFrame {

    /**
     * Creates new form AdminEdit
     */
    public AdminEdit() {
        initComponents();
    }
    PreparedStatement ps;
    ResultSet rs;
    Connection con;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        farm = new javax.swing.JButton();
        labr = new javax.swing.JButton();
        cust = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        custpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        farmpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        labrpanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));

        farm.setBackground(new java.awt.Color(255, 255, 153));
        farm.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        farm.setForeground(new java.awt.Color(0, 0, 0));
        farm.setText("FARM");
        farm.setBorder(null);
        farm.setBorderPainted(false);
        farm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farmActionPerformed(evt);
            }
        });

        labr.setBackground(new java.awt.Color(255, 255, 153));
        labr.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labr.setForeground(new java.awt.Color(0, 0, 0));
        labr.setText("LABR");
        labr.setBorder(null);
        labr.setBorderPainted(false);
        labr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labrActionPerformed(evt);
            }
        });

        cust.setBackground(new java.awt.Color(255, 255, 153));
        cust.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cust.setForeground(new java.awt.Color(0, 0, 0));
        cust.setText("CUST");
        cust.setBorder(null);
        cust.setBorderPainted(false);
        cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(farm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(cust, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(cust, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(farm, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labr, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 100, 630));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        custpanel.setBackground(new java.awt.Color(102, 102, 0));
        custpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ADDRESS", "COUNTRY", "STATE", "PINCODE", "MOBILENO", "EMAIL", "CUSTOMERTYPE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        custpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 40, 880, 540));

        jLayeredPane1.add(custpanel, "card2");

        farmpanel.setBackground(new java.awt.Color(102, 102, 0));
        farmpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "COUNTRY", "STATE", "PINCODE", "MOBILENO", "CROPTYPE", "PRICE", "USERNAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        farmpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 35, 880, 550));

        jLayeredPane1.add(farmpanel, "card3");

        labrpanel.setBackground(new java.awt.Color(102, 102, 0));
        labrpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "COUNTRY", "STATE", "PINCODE", "MOBILENO", "WORKTYPE", "EXPPAYMENT", "USERNAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        labrpanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 41, 890, 550));

        jLayeredPane1.add(labrpanel, "card4");

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 950, 620));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\menuicon.png")); // NOI18N
        jButton1.setText("Logout");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 660, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custActionPerformed
        // TODO add your handling code here:
          jLayeredPane1.removeAll();
        jLayeredPane1.add(custpanel);
        repaint();
        revalidate();
         
    }//GEN-LAST:event_custActionPerformed

    private void farmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farmActionPerformed
        // TODO add your handling code here:
          
        jLayeredPane1.removeAll();
        jLayeredPane1.add(farmpanel);
        repaint();
        revalidate();
    }//GEN-LAST:event_farmActionPerformed

    private void labrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labrActionPerformed
        // TODO add your handling code here:
          jLayeredPane1.removeAll();
        jLayeredPane1.add(labrpanel);
        repaint();
        revalidate();
         
    }//GEN-LAST:event_labrActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         con=MyConnection.getConnection();
         String query1="select * from customerreg";
        try {
           ps=con.prepareStatement(query1);
            rs= ps.executeQuery();
            DefaultTableModel model1=(DefaultTableModel)jTable1.getModel();
            int i=0;
            while(rs.next()){
                String a=rs.getString("Name");
                 String b=rs.getString("ADDRESS");
                  String c=rs.getString("COUNTRY");
                   String d=rs.getString("STATE");
                    String e=rs.getString("PINCODE");
                String f=rs.getString("MOBILENO");
                 String g=rs.getString("EMAIL");
              
                 String k=rs.getString("CUSTOMERTYPE");
                  model1.addRow(new Object[]{a,b,c,d,e,f,k});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
         con=MyConnection.getConnection();
          String query2="select * from farmerreg";
        try {
            ps=con.prepareStatement(query2);
            rs= ps.executeQuery();
            DefaultTableModel model2=(DefaultTableModel)jTable2.getModel();
            int i=0;
            while(rs.next()){
                String aa=rs.getString("NAME");
                 String bb=rs.getString("ADDRESS");
                  String cc=rs.getString("COUNTRY");
                   String dd=rs.getString("STATE");
                    String ee=rs.getString("PINCODE");
                String ff=rs.getString("MOBILENO");
                 String gg=rs.getString("CROPTYPE");
                 String hh=rs.getString("PRICE");
                   String jj=rs.getString("USERNAME");
                  model2.addRow(new Object[]{aa,bb,cc,dd,ee,ff,gg,hh,jj});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
         con=MyConnection.getConnection();
          String query3="select * from labourreg";
        try {
            ps=con.prepareStatement(query3);
            rs= ps.executeQuery();
            DefaultTableModel model3=(DefaultTableModel)jTable3.getModel();
            int i=0;
            while(rs.next()){
                String a1=rs.getString("NAME");
                 String b1=rs.getString("ADDRESS");
                  String c1=rs.getString("COUNTRY");
                   String d1=rs.getString("STATE");
                    String e1=rs.getString("PINCODE");
                String f1=rs.getString("MOBILENO");
                 String g1=rs.getString("WORKTYPE");
                 String h1=rs.getString("EXPPAYMENT");
                   String j1=rs.getString("USERNAME");
                  model3.addRow(new Object[]{a1,b1,c1,d1,e1,f1,g1,h1,j1});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrontEnd FE=new FrontEnd();
        FE.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null,"LOGOUT success");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminEdit().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cust;
    private javax.swing.JPanel custpanel;
    private javax.swing.JButton farm;
    private javax.swing.JPanel farmpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton labr;
    private javax.swing.JPanel labrpanel;
    // End of variables declaration//GEN-END:variables
}
