/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BbmsPack;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */


     

public class CustProf extends javax.swing.JFrame {

    /**
     * Creates new form CustProf
     */
    public CustProf() {
        initComponents();
    }
      PreparedStatement ps;
      ResultSet rs;
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setUndecorated(true);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        nametxt1 = new javax.swing.JLabel();
        addrstxt = new javax.swing.JLabel();
        countxt = new javax.swing.JLabel();
        statetxt = new javax.swing.JLabel();
        pintxt = new javax.swing.JLabel();
        mbltxt = new javax.swing.JLabel();
        mailtxt = new javax.swing.JLabel();
        custtxt = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        fruitspanel = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        foodpanel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        spicespanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custtable = new javax.swing.JTable();
        jButton25 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(127, 255, 212));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\iconprof.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 130, 140));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\menuicon.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jButton2.setBackground(new java.awt.Color(117, 221, 157));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custline.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 30, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Address:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 80, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Country:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 80, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("State:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 60, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Pincode:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 80, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("MobileNo.:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Customer Type:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 150, 30));

        jButton3.setBackground(new java.awt.Color(117, 221, 157));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custquit.png")); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 30, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 680, 10));

        nametxt1.setBackground(new java.awt.Color(102, 255, 255));
        nametxt1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nametxt1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nametxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 210, 30));

        addrstxt.setBackground(new java.awt.Color(255, 255, 255));
        addrstxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addrstxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(addrstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 380, 30));

        countxt.setBackground(new java.awt.Color(255, 255, 255));
        countxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        countxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(countxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 270, 30));

        statetxt.setBackground(new java.awt.Color(255, 255, 255));
        statetxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        statetxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(statetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 260, 30));

        pintxt.setBackground(new java.awt.Color(255, 255, 255));
        pintxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pintxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 230, 30));

        mbltxt.setBackground(new java.awt.Color(255, 255, 255));
        mbltxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mbltxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(mbltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 260, 30));

        mailtxt.setBackground(new java.awt.Color(255, 255, 255));
        mailtxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mailtxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(mailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 320, 30));

        custtxt.setBackground(new java.awt.Color(255, 255, 255));
        custtxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        custtxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(custtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 320, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Fruits");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 190, 50));

        jButton5.setBackground(new java.awt.Color(255, 153, 153));
        jButton5.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Food Crops");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 50));

        jButton6.setBackground(new java.awt.Color(255, 153, 153));
        jButton6.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Spices");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 200, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 680, 50));

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        fruitspanel.setBackground(new java.awt.Color(255, 255, 153));
        fruitspanel.setPreferredSize(new java.awt.Dimension(680, 360));
        fruitspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\pomegranate1.jpg")); // NOI18N
        jButton19.setBorder(null);
        jButton19.setBorderPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        fruitspanel.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 185, 120));

        jButton20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\mango1.jpg")); // NOI18N
        jButton20.setBorder(null);
        jButton20.setBorderPainted(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        fruitspanel.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 185, 120));

        jButton21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\orange1.jpg")); // NOI18N
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        fruitspanel.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 185, 120));

        jButton22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\chikku1.jpg")); // NOI18N
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        fruitspanel.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 185, 120));

        jButton23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\Banana1.jpg")); // NOI18N
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        fruitspanel.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 185, 120));

        jButton24.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\grapes1.jpg")); // NOI18N
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        fruitspanel.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 185, 120));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("pomegranate");
        fruitspanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 100, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("mango");
        fruitspanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("orange");
        fruitspanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 80, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("chikku");
        fruitspanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 80, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("banana");
        fruitspanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 80, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("grapes");
        fruitspanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 80, -1));

        jLayeredPane2.add(fruitspanel, "card4");

        foodpanel.setBackground(new java.awt.Color(255, 255, 153));
        foodpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\ricep.jpg")); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        foodpanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 185, 120));

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\sugarcane1.jpg")); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        foodpanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 185, 120));

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\raagi.jpg")); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        foodpanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 185, 120));

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\wheat.jpg")); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        foodpanel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 185, 120));

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\jla.jpg")); // NOI18N
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        foodpanel.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 185, 120));

        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\cotton1.jpg")); // NOI18N
        jButton15.setBorder(null);
        jButton15.setBorderPainted(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        foodpanel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 185, 120));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("sugarcane");
        foodpanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 80, 20));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("rice");
        foodpanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 50, 20));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("wheat");
        foodpanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 60, 20));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("ragi");
        foodpanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 60, 20));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("maize");
        foodpanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 50, 20));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("cotton");
        foodpanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 50, 20));

        jLayeredPane2.add(foodpanel, "card2");

        spicespanel.setBackground(new java.awt.Color(255, 255, 153));
        spicespanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\cardamom.jpg")); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        spicespanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 185, 120));

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\pepper.jpg")); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        spicespanel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 185, 120));

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\anise.jpg")); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        spicespanel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 185, 120));

        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\garliac1.jpg")); // NOI18N
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        spicespanel.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 185, 120));

        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\ginger.jpg")); // NOI18N
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        spicespanel.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 185, 120));

        jButton18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\turmeric.jpg")); // NOI18N
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        spicespanel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 185, 120));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("cardamom");
        spicespanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 90, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("pepper");
        spicespanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("anise");
        spicespanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("garliac");
        spicespanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 70, 20));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ginger");
        spicespanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 70, 20));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("turmeric");
        spicespanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 70, 20));

        jLayeredPane2.add(spicespanel, "card3");

        jPanel1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 680, 330));

        custtable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        custtable.setForeground(new java.awt.Color(0, 0, 0));
        custtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "MOBILENO", "CROPTYPE", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        custtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(custtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 640, 100));

        jButton25.setBackground(new java.awt.Color(255, 204, 51));
        jButton25.setForeground(new java.awt.Color(255, 51, 51));
        jButton25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\icons8_buy_50px_1.png")); // NOI18N
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 520, 50, 70));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("BUY");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 595, 30, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrontEnd FE=new FrontEnd();
        FE.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null,"LOGOUT success");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int count1=evt.getClickCount();
        if(0!=count1%2){
            this.setState(FrontEnd.ICONIFIED);
        }
        else
        {
            this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      
   //String value= CustProf.getTextfieldValue();

   // nametxt1.setText(CustLog.mailtxt.getText());
     
        String mail1ex=CustLog.mailtxt.getText();
      Connection con=MyConnection.getConnection();
       String query="select Name,ADDRESS,COUNTRY,STATE,PINCODE,MOBILENO,EMAIL,CUSTOMERTYPE from customerreg where EMAIL=?";
        try {
            ps=con.prepareStatement(query);
             ps.setString(1,mail1ex);
               rs= ps.executeQuery();
               while(rs.next()){
                   String name=rs.getString("Name");
                   nametxt1.setText(name); 
                   String addr=rs.getString("ADDRESS");
                 
                   addrstxt.setText(addr);
                  String cou=rs.getString("COUNTRY");
                  countxt.setText(cou);
                  String sts=rs.getString("STATE");
                  statetxt.setText(sts);
                  String pinc=rs.getString("PINCODE");
                  pintxt.setText(pinc);
                  String mbl=rs.getString("MOBILENO");
                  mbltxt.setText(mbl);
                 String mai=rs.getString("EMAIL");
                 mailtxt.setText(mai);
                  String cut=rs.getString("CUSTOMERTYPE");
                  custtxt.setText(cut);
               }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
    }//GEN-LAST:event_formWindowOpened

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
  
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jLayeredPane2.removeAll();
        jLayeredPane2.add(foodpanel);
        repaint();
        revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
           jLayeredPane2.removeAll();
        jLayeredPane2.add(spicespanel);
        repaint();
        revalidate();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         jLayeredPane2.removeAll();
        jLayeredPane2.add(fruitspanel);
        repaint();
        revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='rice'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

  Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='pepper'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
             while(model.getRowCount()>0){
                model.removeRow(0);
            }
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='anise'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='garliac'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='ginger'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='cardamom'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='wheat'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='ragi'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='maize'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='mango'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='orange'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='chikku'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='banana'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='grapes'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='pomegranate'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
                 Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='cotton'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
                 Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,CROPTYPE,PRICE from farmerreg where CROPTYPE='sugarcane'";
        try {
            rs= ps.executeQuery(query);
            DefaultTableModel model=(DefaultTableModel)custtable.getModel();
            model.setRowCount(0);
            custtable.repaint();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("CROPTYPE");
                 String d=rs.getString("PRICE");
                  model.addRow(new Object[]{a,b,c,d});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void custtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custtableMouseClicked
        // TODO add your handling code here:
      
        // create query
      
    }//GEN-LAST:event_custtableMouseClicked

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
            DefaultTableModel dl=(DefaultTableModel)custtable.getModel();
        int selectIndex=custtable.getSelectedRow();
        //String username=LabrLog.usertxt.getText();
      String farname=dl.getValueAt(selectIndex,0).toString();
      // dl.getValueAt(selectIndex,1).toString();
        
        String name1=nametxt1.getText();
        String addrs1=addrstxt.getText();
        String pin=pintxt.getText();
         String query="insert into ordlist(CustName,Address,pincode,FarmName)values(?,?,?,?)";
        try {
             ps=MyConnection.getConnection().prepareStatement(query);
             ps.setString(1,name1);
              ps.setString(2,addrs1);
              ps.setString(3,pin);
               ps.setString(4,farname);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Order success");
          
        } catch (SQLException ex) {
            Logger.getLogger(CustProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustProf().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrstxt;
    private javax.swing.JLabel countxt;
    private javax.swing.JTable custtable;
    private javax.swing.JLabel custtxt;
    private javax.swing.JPanel foodpanel;
    private javax.swing.JPanel fruitspanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mailtxt;
    private javax.swing.JLabel mbltxt;
    private javax.swing.JLabel nametxt1;
    private javax.swing.JLabel pintxt;
    private javax.swing.JPanel spicespanel;
    private javax.swing.JLabel statetxt;
    // End of variables declaration//GEN-END:variables
}
