/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BbmsPack;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */
public class CustReg extends javax.swing.JFrame {

    /**
     * Creates new form CustReg
     */
    public CustReg() {
        initComponents();
    }
    public boolean checkEmail(String email)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkemail=false;
        String query="select * from customerreg where EMAIL=?";
        try{
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, email);
            rs=ps.executeQuery();
            if(rs.next())
            {
                checkemail=true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkemail;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        setUndecorated(true);
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        nametxt = new javax.swing.JTextField();
        addrstxt = new javax.swing.JTextField();
        countxt = new javax.swing.JTextField();
        statetxt = new javax.swing.JTextField();
        pintxt = new javax.swing.JTextField();
        mbltxt = new javax.swing.JTextField();
        mailtxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JPasswordField();
        repasstxt = new javax.swing.JPasswordField();
        custtxt = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(117, 221, 157));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(117, 221, 157));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("REGISTRATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 350, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 350, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 350, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, 350, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 350, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 350, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 720, 350, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 350, 10));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Pincode:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 80, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 60, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("MobileNo.:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 100, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Email:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 60, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Password:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 100, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Retype Pass:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 120, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Customer Type:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 150, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Address:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 80, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Country:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 80, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 350, 10));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("State:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 330, 60, 30));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 350, 10));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 350, 10));

        nametxt.setBackground(new java.awt.Color(117, 221, 157));
        nametxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nametxt.setForeground(new java.awt.Color(0, 0, 51));
        nametxt.setBorder(null);
        jPanel2.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 139, 350, 30));

        addrstxt.setBackground(new java.awt.Color(117, 221, 157));
        addrstxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addrstxt.setForeground(new java.awt.Color(0, 0, 51));
        addrstxt.setBorder(null);
        jPanel2.add(addrstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 209, 350, 30));

        countxt.setBackground(new java.awt.Color(117, 221, 157));
        countxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        countxt.setForeground(new java.awt.Color(0, 0, 51));
        countxt.setBorder(null);
        jPanel2.add(countxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 269, 350, 30));

        statetxt.setBackground(new java.awt.Color(117, 221, 157));
        statetxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        statetxt.setForeground(new java.awt.Color(0, 0, 51));
        statetxt.setBorder(null);
        jPanel2.add(statetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 329, 350, 30));

        pintxt.setBackground(new java.awt.Color(117, 221, 157));
        pintxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pintxt.setForeground(new java.awt.Color(0, 0, 51));
        pintxt.setBorder(null);
        jPanel2.add(pintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 389, 350, 30));

        mbltxt.setBackground(new java.awt.Color(117, 221, 157));
        mbltxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mbltxt.setForeground(new java.awt.Color(0, 0, 51));
        mbltxt.setBorder(null);
        jPanel2.add(mbltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 449, 350, 30));

        mailtxt.setBackground(new java.awt.Color(117, 221, 157));
        mailtxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mailtxt.setForeground(new java.awt.Color(0, 0, 51));
        mailtxt.setBorder(null);
        jPanel2.add(mailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 509, 350, 30));

        passtxt.setBackground(new java.awt.Color(117, 221, 157));
        passtxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        passtxt.setForeground(new java.awt.Color(0, 0, 51));
        passtxt.setBorder(null);
        jPanel2.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 569, 350, 30));

        repasstxt.setBackground(new java.awt.Color(117, 221, 157));
        repasstxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        repasstxt.setForeground(new java.awt.Color(0, 0, 51));
        repasstxt.setBorder(null);
        jPanel2.add(repasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 629, 350, 30));

        custtxt.setBackground(new java.awt.Color(117, 221, 157));
        custtxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        custtxt.setForeground(new java.awt.Color(0, 0, 51));
        custtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Consumer", "Retailer", "Wholesaler" }));
        custtxt.setToolTipText("");
        custtxt.setName("select"); // NOI18N
        jPanel2.add(custtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 690, 350, 30));

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("submit");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 760, 70, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("cancel");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 760, 70, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 570, 820));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custquit.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 30, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custline.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
          int count1=evt.getClickCount();
        if(0!=count1%2){
         this.setState(FrontEnd.ICONIFIED);
        }
                    else
        {
        this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CustLog CL1=new CustLog();
        CL1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Name=nametxt.getText();
        String Address=addrstxt.getText();
        String Country=countxt.getText();
        String State=statetxt.getText();
        String Pincode=pintxt.getText();
        String MobileNo=mbltxt.getText();
        String Email=mailtxt.getText();
        String Password=String.valueOf(passtxt.getPassword());
        String Retypepass=String.valueOf(repasstxt.getPassword());
        String Custtype=(String)custtxt.getSelectedItem();
        if(Name.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter A Name");
        }
        else if(Address.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter An Address");
        }
        else if(Country.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter A Country");
        }
          else if(State.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter A State");
        }
           else if(Pincode.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter A Pincode");
        }
            else if(MobileNo.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add A Mobile Number");
        }
             else if(Email.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add An Email");
        }
              else if(Password.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add A Password");
        }
               else if(!Password.equals(Retypepass))
        {
            JOptionPane.showMessageDialog(null,"Password is not matching Please retype again");
        }
        if(checkEmail(Email))
        {
            JOptionPane.showMessageDialog(null,"Entered Email is already exist");
        }
         PreparedStatement ps;
         String query="insert into customerreg(Name,ADDRESS,COUNTRY,STATE,PINCODE,MOBILENO,EMAIL,PASSWORD,RETYPEPASS,CUSTOMERTYPE)values(?,?,?,?,?,?,?,?,?,?)";
         
         try{
             ps=MyConnection.getConnection().prepareStatement(query);
             ps.setString(1, Name);
             ps.setString(2, Address);
              ps.setString(3, Country);
               ps.setString(4, State);
                ps.setString(5, Pincode);
                 ps.setString(6, MobileNo);
                  ps.setString(7, Email);
                   ps.setString(8, Password);
                    ps.setString(9, Retypepass);
                     ps.setString(10, Custtype);
                 if(!Name.equals("")){
                   if(!Address.equals("")){ 
                   if(!Country.equals("")){ 
                    if(!State.equals("")){ 
                    if(!Pincode.equals("")){ 
                     if(!MobileNo.equals("")){
                     if(!Email.equals("")){
                         if(!Custtype.equals("")){
                  if(Password.equals(Retypepass)){
                     ps.executeUpdate();
                   JOptionPane.showMessageDialog(null,"New Customer Added");
                   CustLog cll=new CustLog();
             cll.setVisible(true);
             this.dispose();    }}}}}}}}}
            
         } catch (SQLException ex) {
            Logger.getLogger(CustReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustReg().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrstxt;
    private javax.swing.JTextField countxt;
    private javax.swing.JComboBox<String> custtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField mailtxt;
    private javax.swing.JTextField mbltxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JTextField pintxt;
    private javax.swing.JPasswordField repasstxt;
    private javax.swing.JTextField statetxt;
    // End of variables declaration//GEN-END:variables
}
