/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BbmsPack;

import static BbmsPack.LabrProf.fpaddtxt;
import static BbmsPack.LabrProf.fpnametxt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */


     

public class FarmProf extends javax.swing.JFrame {

    

    /**
     * Creates new form CustProf
     */
    public FarmProf() {
        initComponents();
    }
      PreparedStatement ps;
      ResultSet rs;
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setUndecorated(true);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        nametxt1 = new javax.swing.JLabel();
        addrstxt = new javax.swing.JLabel();
        countxt = new javax.swing.JLabel();
        statetxt = new javax.swing.JLabel();
        pintxt = new javax.swing.JLabel();
        mbltxt = new javax.swing.JLabel();
        croptxt = new javax.swing.JLabel();
        pricetxt = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtuser = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabletxt = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordtable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(127, 255, 212));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\iconprof.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 130, 140));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\menuicon.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jButton2.setBackground(new java.awt.Color(117, 221, 157));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custline.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 30, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("CropType:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Address:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Country:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("State:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 60, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Pincode:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 80, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("MobileNo.:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("UserName:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, 30));

        jButton3.setBackground(new java.awt.Color(117, 221, 157));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custquit.png")); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 30, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 630, 10));

        nametxt1.setBackground(new java.awt.Color(102, 255, 255));
        nametxt1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nametxt1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nametxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 290, 30));

        addrstxt.setBackground(new java.awt.Color(255, 255, 255));
        addrstxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addrstxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(addrstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 290, 30));

        countxt.setBackground(new java.awt.Color(255, 255, 255));
        countxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        countxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(countxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 270, 30));

        statetxt.setBackground(new java.awt.Color(255, 255, 255));
        statetxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        statetxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(statetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 260, 30));

        pintxt.setBackground(new java.awt.Color(255, 255, 255));
        pintxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pintxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 230, 30));

        mbltxt.setBackground(new java.awt.Color(255, 255, 255));
        mbltxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mbltxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(mbltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 260, 30));

        croptxt.setBackground(new java.awt.Color(255, 255, 255));
        croptxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        croptxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(croptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 320, 30));

        pricetxt.setBackground(new java.awt.Color(255, 255, 255));
        pricetxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pricetxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 320, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Price/1Kg:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 100, 30));

        txtuser.setBackground(new java.awt.Color(255, 255, 255));
        txtuser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtuser.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 240, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Search here for workers");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 280, 30));

        searchtxt.setBackground(new java.awt.Color(255, 204, 204));
        searchtxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        searchtxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 270, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText(" Select the worker from table and make call for CONFIRMATION ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 490, -1));

        tabletxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tabletxt.setForeground(new java.awt.Color(0, 0, 0));
        tabletxt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "MOBILENO", "PINCODE", "WORKTYPE", "EXPPAYMENT", "USERNAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabletxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabletxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletxtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabletxt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 590, 170));

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\icons8_search_30px.png")); // NOI18N
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 50, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Note: Please enter your pincode so that you  can choose nearest workers");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 520, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 630, 330));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 630, 10));

        ordtable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ordtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustName", "Address", "pincode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ordtable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(ordtable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, -1, 110));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("LIST:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 60, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("ORDER");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrontEnd FE=new FrontEnd();
        FE.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null,"LOGOUT success");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int count1=evt.getClickCount();
        if(0!=count1%2){
            this.setState(FrontEnd.ICONIFIED);
        }
        else
        {
            this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      
  
        String userex=FarmLog.usertxt.getText();
      Connection con=MyConnection.getConnection();
       String query="select NAME,ADDRESS,COUNTRY,STATE,PINCODE,MOBILENO,CROPTYPE,PRICE,USERNAME from farmerreg where USERNAME=?";
        try {
            ps=con.prepareStatement(query);
             ps.setString(1,userex);
               rs= ps.executeQuery();
               while(rs.next()){
                   String name=rs.getString("NAME");
                   nametxt1.setText(name); 
                   String addr=rs.getString("ADDRESS");
                 
                   addrstxt.setText(addr);
                  String cou=rs.getString("COUNTRY");
                  countxt.setText(cou);
                  String sts=rs.getString("STATE");
                  statetxt.setText(sts);
                  String pinc=rs.getString("PINCODE");
                  pintxt.setText(pinc);
                  String mbl=rs.getString("MOBILENO");
                  mbltxt.setText(mbl);
                 String mai=rs.getString("CROPTYPE");
                 croptxt.setText(mai);
                  String cut=rs.getString("PRICE");
                  pricetxt.setText(cut);
                  String userna=rs.getString("USERNAME");
                  txtuser.setText(userna);
               }
               try {
            // Connection con=MyConnection.getConnection();
             DefaultTableModel model=(DefaultTableModel)ordtable.getModel();
            String farmname=nametxt1.getText();
             String query1="select CustName,Address,pincode,FarmName from ordlist where FarmName=?";
            
               ps=con.prepareStatement(query1);
                ps.setString(1,farmname);
           
               
                
                rs= ps.executeQuery();
                
                int i=0;
               while(rs.next()){
                    String a=rs.getString("CustName");
                String b=rs.getString("Address");
                 String c=rs.getString("pincode");
                 
                  model.addRow(new Object[]{a,b,c});
                  i++;
                  }} 
        catch (SQLException ex) {
            Logger.getLogger(FarmProf.class.getName()).log(Level.SEVERE, null, ex);
        }  
        } catch (SQLException ex) {
            Logger.getLogger(FarmProf.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
    }//GEN-LAST:event_formWindowOpened

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
  
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String search=searchtxt.getText();
         Connection con=MyConnection.getConnection();
    String query="select NAME,MOBILENO,PINCODE,WORKTYPE,EXPPAYMENT,USERNAME from labourreg where PINCODE=?";
        try {
             ps=MyConnection.getConnection().prepareStatement(query);
             ps.setString(1,search);
            rs= ps.executeQuery();
            DefaultTableModel model=(DefaultTableModel)tabletxt.getModel();
            int i=0;
            while(rs.next()){
                String a=rs.getString("NAME");
                String b=rs.getString("MOBILENO");
                 String c=rs.getString("PINCODE");
                 String d=rs.getString("WORKTYPE");
                 String e=rs.getString("EXPPAYMENT");
                 String f=rs.getString("USERNAME");
                  model.addRow(new Object[]{a,b,c,d,e,f});
                  i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FarmProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabletxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletxtMouseClicked
        // TODO add your handling code here:
          DefaultTableModel dl=(DefaultTableModel)tabletxt.getModel();
        int selectIndex=tabletxt.getSelectedRow();
        //String username=LabrLog.usertxt.getText();
      String labrname=dl.getValueAt(selectIndex,5).toString();
      // dl.getValueAt(selectIndex,1).toString();
        
        String name1=txtuser.getText();
        String addrs1=addrstxt.getText();
        // create query
         String query="insert into selectedlabr(USERNAME,ADDRESS,LNAME)values(?,?,?)";
        try {
             ps=MyConnection.getConnection().prepareStatement(query);
             ps.setString(1,name1);
              ps.setString(2,addrs1);
              ps.setString(3,labrname);
            ps.executeUpdate();
             
                 
        } catch (SQLException ex) {
            Logger.getLogger(FarmProf.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          
             
        
             
         
    }//GEN-LAST:event_tabletxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FarmProf().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrstxt;
    private javax.swing.JLabel countxt;
    private javax.swing.JLabel croptxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel mbltxt;
    private javax.swing.JLabel nametxt1;
    public javax.swing.JTable ordtable;
    private javax.swing.JLabel pintxt;
    private javax.swing.JLabel pricetxt;
    public static javax.swing.JTextField searchtxt;
    private javax.swing.JLabel statetxt;
    private javax.swing.JTable tabletxt;
    public static javax.swing.JLabel txtuser;
    // End of variables declaration//GEN-END:variables
}
