/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BbmsPack;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */


     

public class LabrProf extends javax.swing.JFrame {

    /**
     * Creates new form CustProf
     */
    public LabrProf() {
        initComponents();
    }
      PreparedStatement ps;
      ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setUndecorated(true);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lpnametxt = new javax.swing.JLabel();
        lpaddtxt = new javax.swing.JLabel();
        lpcountxt = new javax.swing.JLabel();
        lpstatetxt = new javax.swing.JLabel();
        lppintxt = new javax.swing.JLabel();
        lpmbltxt = new javax.swing.JLabel();
        lpworktxt = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lpusertxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        fpnametxt = new javax.swing.JLabel();
        fpaddtxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lppaytxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(127, 255, 212));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\iconprof.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 130, 140));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\menuicon.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jButton2.setBackground(new java.awt.Color(117, 221, 157));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custline.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 30, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("UserName:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 100, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Country:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 80, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("State:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 60, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Pincode:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 80, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("MobileNo.:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Exp.Payment/Day:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, 30));

        jButton3.setBackground(new java.awt.Color(117, 221, 157));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custquit.png")); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 30, 30));

        lpnametxt.setBackground(new java.awt.Color(102, 255, 255));
        lpnametxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lpnametxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lpnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 310, 30));

        lpaddtxt.setBackground(new java.awt.Color(255, 255, 255));
        lpaddtxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lpaddtxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lpaddtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 290, 30));

        lpcountxt.setBackground(new java.awt.Color(255, 255, 255));
        lpcountxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lpcountxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lpcountxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 270, 30));

        lpstatetxt.setBackground(new java.awt.Color(255, 255, 255));
        lpstatetxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lpstatetxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lpstatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 260, 30));

        lppintxt.setBackground(new java.awt.Color(255, 255, 255));
        lppintxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lppintxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lppintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 230, 30));

        lpmbltxt.setBackground(new java.awt.Color(255, 255, 255));
        lpmbltxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lpmbltxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lpmbltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 260, 30));

        lpworktxt.setBackground(new java.awt.Color(255, 255, 255));
        lpworktxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lpworktxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lpworktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 270, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("WorkType:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 100, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Address:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 80, 30));

        lpusertxt.setBackground(new java.awt.Color(255, 255, 255));
        lpusertxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lpusertxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lpusertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 260, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 600, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fpnametxt.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        fpnametxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(fpnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 170, 30));

        fpaddtxt.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        fpaddtxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(fpaddtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 250, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("from");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 15, 50, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 170, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 170, 10));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("So that you will receive call from farmer for CONFIRMATION");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 540, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("is selected you to work for his agriculture activity");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 480, 30));

        jButton4.setBackground(new java.awt.Color(51, 0, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 255, 51));
        jButton4.setText("OKAY");
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 600, 210));

        lppaytxt.setBackground(new java.awt.Color(255, 255, 255));
        lppaytxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lppaytxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lppaytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrontEnd FE=new FrontEnd();
        FE.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null,"LOGOUT success");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int count1=evt.getClickCount();
        if(0!=count1%2){
            this.setState(FrontEnd.ICONIFIED);
        }
        else
        {
            this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      
   //String value= CustProf.getTextfieldValue();

   // nametxt1.setText(CustLog.mailtxt.getText());
     
        String userex=LabrLog.usertxt.getText();
      Connection con=MyConnection.getConnection();
       String query="select NAME,ADDRESS,COUNTRY,STATE,PINCODE,MOBILENO,WORKTYPE,EXPPAYMENT,USERNAME from labourreg where USERNAME=?";
      
        try {
            ps=con.prepareStatement(query);
             ps.setString(1,userex);
               rs= ps.executeQuery();
               while(rs.next()){
                   String name=rs.getString("NAME");
                   lpnametxt.setText(name); 
                   String addr=rs.getString("ADDRESS");
                 
                   lpaddtxt.setText(addr);
                  String cou=rs.getString("COUNTRY");
                  lpcountxt.setText(cou);
                  String sts=rs.getString("STATE");
                  lpstatetxt.setText(sts);
                  String pinc=rs.getString("PINCODE");
                  lppintxt.setText(pinc);
                  String mbl=rs.getString("MOBILENO");
                  lpmbltxt.setText(mbl);
                 
                  String work=rs.getString("WORKTYPE");
                  lpworktxt.setText(work);
                   String pay=rs.getString("EXPPAYMENT");
                  lppaytxt.setText(pay);
                    String use=rs.getString("USERNAME");
                  lpusertxt.setText(use);
               }
             
              try {
            String userex1=LabrLog.usertxt.getText();
                       String query1="select USERNAME,ADDRESS,LNAME from selectedlabr where LNAME=?";
                     ps=con.prepareStatement(query1);
           
               
                ps.setString(1,userex1);
                rs= ps.executeQuery();
               while(rs.next()){
                   
                  // String name=lpnametxt.getText();
                   String name1=rs.getString("USERNAME");
                 
               String add1=rs.getString("ADDRESS");
               //if(name.equals(name1)){
                 fpnametxt.setText(name1);
                   fpaddtxt.setText(add1);}} 
        catch (SQLException ex) {
            Logger.getLogger(LabrProf.class.getName()).log(Level.SEVERE, null, ex);
        }          
                  
                  
               
        } catch (SQLException ex) {
            Logger.getLogger(LabrProf.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      //  Connection con=MyConnection.getConnection();
      
       
        
                 
    }//GEN-LAST:event_formWindowOpened

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
  
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String luser=lpusertxt.getText();
         String query="delete from selectedlabr where LNAME=?";
        try {
             ps=MyConnection.getConnection().prepareStatement(query);
             ps.setString(1,luser);
             
            ps.executeUpdate();
            fpnametxt.setText("");
            fpaddtxt.setText("");
          
        } catch (SQLException ex) {
            Logger.getLogger(FarmProf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabrProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LabrProf().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel fpaddtxt;
    public static javax.swing.JLabel fpnametxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lpaddtxt;
    private javax.swing.JLabel lpcountxt;
    private javax.swing.JLabel lpmbltxt;
    private javax.swing.JLabel lpnametxt;
    private javax.swing.JLabel lppaytxt;
    private javax.swing.JLabel lppintxt;
    private javax.swing.JLabel lpstatetxt;
    private javax.swing.JLabel lpusertxt;
    private javax.swing.JLabel lpworktxt;
    // End of variables declaration//GEN-END:variables
}
