/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BbmsPack;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */
public class LabrReg extends javax.swing.JFrame {

    /**
     * Creates new form CustReg
     */
    public LabrReg() {
        initComponents();
    }
    
     public boolean checkUser(String user)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkuser=false;
        String query="select * from labourreg where USERNAME=?";
        try{
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, user);
            rs=ps.executeQuery();
            if(rs.next())
            {
                checkuser=true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkuser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        setUndecorated(true);
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        lnametxt = new javax.swing.JTextField();
        laddrstxt = new javax.swing.JTextField();
        lcountxt = new javax.swing.JTextField();
        lstatetxt = new javax.swing.JTextField();
        lpintxt = new javax.swing.JTextField();
        lmbltxt = new javax.swing.JTextField();
        lusertxt = new javax.swing.JTextField();
        lpasstxt = new javax.swing.JPasswordField();
        lrepasstxt = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lworktxt = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        lpaytxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(117, 221, 157));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(117, 221, 157));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("REGISTRATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 350, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 350, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 350, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 750, 350, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 350, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 680, 350, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 820, 350, 10));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Pincode:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 80, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 60, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("MobileNo.:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 100, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Password:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, 100, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Retype Pass:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 790, 120, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("UserName:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 100, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Address:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 80, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Country:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 80, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 350, 10));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("State:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 60, 30));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 350, 10));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 350, 10));

        lnametxt.setBackground(new java.awt.Color(117, 221, 157));
        lnametxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lnametxt.setForeground(new java.awt.Color(0, 0, 51));
        lnametxt.setBorder(null);
        jPanel2.add(lnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 139, 350, 30));

        laddrstxt.setBackground(new java.awt.Color(117, 221, 157));
        laddrstxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        laddrstxt.setForeground(new java.awt.Color(0, 0, 51));
        laddrstxt.setBorder(null);
        jPanel2.add(laddrstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 350, 30));

        lcountxt.setBackground(new java.awt.Color(117, 221, 157));
        lcountxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lcountxt.setForeground(new java.awt.Color(0, 0, 51));
        lcountxt.setBorder(null);
        jPanel2.add(lcountxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 350, 30));

        lstatetxt.setBackground(new java.awt.Color(117, 221, 157));
        lstatetxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lstatetxt.setForeground(new java.awt.Color(0, 0, 51));
        lstatetxt.setBorder(null);
        jPanel2.add(lstatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 350, 30));

        lpintxt.setBackground(new java.awt.Color(117, 221, 157));
        lpintxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lpintxt.setForeground(new java.awt.Color(0, 0, 51));
        lpintxt.setBorder(null);
        jPanel2.add(lpintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 350, 30));

        lmbltxt.setBackground(new java.awt.Color(117, 221, 157));
        lmbltxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lmbltxt.setForeground(new java.awt.Color(0, 0, 51));
        lmbltxt.setBorder(null);
        jPanel2.add(lmbltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 350, 30));

        lusertxt.setBackground(new java.awt.Color(117, 221, 157));
        lusertxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lusertxt.setForeground(new java.awt.Color(0, 0, 51));
        lusertxt.setBorder(null);
        jPanel2.add(lusertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 350, 30));

        lpasstxt.setBackground(new java.awt.Color(117, 221, 157));
        lpasstxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lpasstxt.setForeground(new java.awt.Color(0, 0, 51));
        lpasstxt.setBorder(null);
        jPanel2.add(lpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 720, 350, 30));

        lrepasstxt.setBackground(new java.awt.Color(117, 221, 157));
        lrepasstxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lrepasstxt.setForeground(new java.awt.Color(0, 0, 51));
        lrepasstxt.setBorder(null);
        lrepasstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrepasstxtActionPerformed(evt);
            }
        });
        jPanel2.add(lrepasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 790, 350, 30));

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("submit");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 860, 70, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("cancel");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 860, 70, 30));

        lworktxt.setBackground(new java.awt.Color(117, 221, 157));
        lworktxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lworktxt.setForeground(new java.awt.Color(0, 0, 51));
        lworktxt.setBorder(null);
        jPanel2.add(lworktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 350, 30));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 350, 10));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Work Type:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 110, 30));

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 350, 10));

        lpaytxt.setBackground(new java.awt.Color(117, 221, 157));
        lpaytxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lpaytxt.setForeground(new java.awt.Color(0, 0, 51));
        lpaytxt.setBorder(null);
        jPanel2.add(lpaytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 350, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText(" Payment/Day:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 130, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 570, 920));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custquit.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 30, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\BBMSproj\\src\\BbmsPack\\custline.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
          int count1=evt.getClickCount();
        if(0!=count1%2){
         this.setState(FrontEnd.ICONIFIED);
        }
                    else
        {
        this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LabrLog LL1=new LabrLog();
        LL1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lrepasstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrepasstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lrepasstxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         String Name=lnametxt.getText();
        String Address=laddrstxt.getText();
        String Country=lcountxt.getText();
        String State=lstatetxt.getText();
        String Pincode=lpintxt.getText();
        String MobileNo=lmbltxt.getText();
       
        String Worktype=lworktxt.getText();
        String Payment=lpaytxt.getText();
        String Username=lusertxt.getText();
        String Password=String.valueOf(lpasstxt.getPassword());
        String Retypepass=String.valueOf(lrepasstxt.getPassword());
       
        if(Name.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter A Name");
        }
        else if(Address.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter An Address");
        }
        else if(Country.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter A Country");
        }
          else if(State.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter A State");
        }
           else if(Pincode.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter A Pincode");
        }
            else if(MobileNo.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add A Mobile Number");
        }
          
              else if(Worktype.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add An Work type");
        }
               else if(Payment.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add An payment per day");
        }
                 else if(Username.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add An Username");
        }
              else if(Password.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Add A Password");
        }
               else if(!Password.equals(Retypepass))
        {
            JOptionPane.showMessageDialog(null,"Password is not matching Please retype again");
        }
        if(checkUser(Username))
        {
            JOptionPane.showMessageDialog(null,"Entered Username is already exist");
        }
         PreparedStatement ps;
         String query="insert into labourreg(NAME,ADDRESS,COUNTRY,STATE,PINCODE,MOBILENO,WORKTYPE,EXPPAYMENT,USERNAME,PASSWORD,RETYPEPASS)values(?,?,?,?,?,?,?,?,?,?,?)";
         
         try{
             ps=MyConnection.getConnection().prepareStatement(query);
             ps.setString(1, Name);
             ps.setString(2, Address);
              ps.setString(3, Country);
               ps.setString(4, State);
                ps.setString(5, Pincode);
                 ps.setString(6, MobileNo);
                
                  ps.setString(7,Worktype);
                  ps.setString(8,Payment);
                  ps.setString(9,Username);
                   ps.setString(10, Password);
                    ps.setString(11, Retypepass);
                     
                  if(!Name.equals("")){
                   if(!Address.equals("")){ 
                   if(!Country.equals("")){ 
                    if(!State.equals("")){ 
                    if(!Pincode.equals("")){ 
                     if(!MobileNo.equals("")){
                     if(!Worktype.equals("")){
                         if(!Payment.equals("")){
                      if(!Username.equals("")){
                  if(Password.equals(Retypepass)){
                    ps.executeUpdate();
                  JOptionPane.showMessageDialog(null,"New Labour information Added");
                  LabrLog lll=new LabrLog();
             lll.setVisible(true);
             this.dispose();}}}}}}}}}}
             
         } catch (SQLException ex) {
            Logger.getLogger(CustReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabrReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabrReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabrReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabrReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabrReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField laddrstxt;
    private javax.swing.JTextField lcountxt;
    private javax.swing.JTextField lmbltxt;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JPasswordField lpasstxt;
    private javax.swing.JTextField lpaytxt;
    private javax.swing.JTextField lpintxt;
    private javax.swing.JPasswordField lrepasstxt;
    private javax.swing.JTextField lstatetxt;
    private javax.swing.JTextField lusertxt;
    private javax.swing.JTextField lworktxt;
    // End of variables declaration//GEN-END:variables
}
